<?php
/**
 * Handles nonce-protected PDF download and regenerate requests.
 *
 * @package InvoiceForge
 */

namespace InvoiceForge\Admin;

defined( 'ABSPATH' ) || exit;

/**
 * Routes `invoiceforge_action` query-string requests:
 *
 *   ?invoiceforge_action=download_invoice&order_id=123&_wpnonce=...
 *   ?invoiceforge_action=regenerate_invoice&order_id=123&_wpnonce=...
 *   ?invoiceforge_action=download_packing_slip&order_id=123&_wpnonce=...
 *
 * All requests require a valid nonce AND appropriate capability.
 */
class Download_Handler {

	public function init(): void {
		add_action( 'admin_init', [ $this, 'handle' ] );
		add_action( 'init', [ $this, 'handle_frontend' ] );
	}

	/**
	 * Handles admin-context requests (manage_woocommerce required for regenerate).
	 */
	public function handle(): void {
		// phpcs:disable WordPress.Security.NonceVerification.Recommended -- nonce verified below via check_admin_referer before any privileged action.
		if ( ! isset( $_GET['invoiceforge_action'] ) ) {
			return;
		}
		$action   = sanitize_key( wp_unslash( $_GET['invoiceforge_action'] ) );
		$order_id = isset( $_GET['order_id'] ) ? absint( $_GET['order_id'] ) : 0;
		// phpcs:enable WordPress.Security.NonceVerification.Recommended

		if ( ! $order_id ) {
			return;
		}

		$nonce_prefix = ( 0 === strpos( $action, 'regenerate_' ) )
			? 'invoiceforge_regenerate_'
			: 'invoiceforge_download_';
		check_admin_referer( $nonce_prefix . $order_id );

		switch ( $action ) {
			case 'download_invoice':
				$this->download_invoice( $order_id );
				break;

			case 'download_packing_slip':
				$this->download_packing_slip( $order_id );
				break;

			case 'regenerate_invoice':
				$this->regenerate_invoice( $order_id );
				break;

			case 'regenerate_packing_slip':
				$this->regenerate_packing_slip( $order_id );
				break;
		}
	}

	/**
	 * Handles frontend-context download requests (customer My Account).
	 */
	public function handle_frontend(): void {
		// phpcs:disable WordPress.Security.NonceVerification.Recommended -- nonce verified below via check_admin_referer before any privileged action.
		if ( is_admin() || ! isset( $_GET['invoiceforge_action'] ) ) {
			return;
		}
		$action   = sanitize_key( wp_unslash( $_GET['invoiceforge_action'] ) );
		$order_id = isset( $_GET['order_id'] ) ? absint( $_GET['order_id'] ) : 0;
		// phpcs:enable WordPress.Security.NonceVerification.Recommended

		if ( ! $order_id || 'download_invoice' !== $action ) {
			return;
		}

		check_admin_referer( 'invoiceforge_download_' . $order_id );
		$this->download_invoice( $order_id );
	}

	/**
	 * Downloads the invoice PDF for an order.
	 *
	 * @param int $order_id Order ID.
	 */
	private function download_invoice( int $order_id ): void {
		if ( ! invoiceforge_current_user_can_view( $order_id ) ) {
			wp_die( esc_html__( 'Permission denied.', 'invoiceforge-for-woocommerce' ) );
		}

		$order = wc_get_order( $order_id );
		if ( ! $order ) {
			wp_die( esc_html__( 'Order not found.', 'invoiceforge-for-woocommerce' ) );
		}

		$generator = new \InvoiceForge\PDF\PDF_Generator();
		$generator->stream( new \InvoiceForge\PDF\Invoice_Document( $order ) );
	}

	/**
	 * Downloads the packing slip PDF for an order.
	 *
	 * @param int $order_id Order ID.
	 */
	private function download_packing_slip( int $order_id ): void {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_die( esc_html__( 'Permission denied.', 'invoiceforge-for-woocommerce' ) );
		}

		$order = wc_get_order( $order_id );
		if ( ! $order ) {
			wp_die( esc_html__( 'Order not found.', 'invoiceforge-for-woocommerce' ) );
		}

		$generator = new \InvoiceForge\PDF\PDF_Generator();
		$generator->stream( new \InvoiceForge\PDF\Packing_Slip_Document( $order ) );
	}

	/**
	 * Regenerates the invoice PDF for an order (admin only).
	 *
	 * @param int $order_id Order ID.
	 */
	private function regenerate_invoice( int $order_id ): void {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_die( esc_html__( 'Permission denied.', 'invoiceforge-for-woocommerce' ) );
		}

		$order = wc_get_order( $order_id );
		if ( ! $order ) {
			wp_die( esc_html__( 'Order not found.', 'invoiceforge-for-woocommerce' ) );
		}

		$generator = new \InvoiceForge\PDF\PDF_Generator();
		$generator->generate( new \InvoiceForge\PDF\Invoice_Document( $order ) );

		$order->add_order_note( __( 'Invoice (PDF) regenerated by InvoiceForge.', 'invoiceforge-for-woocommerce' ) );

		$redirect = wp_nonce_url(
			add_query_arg( [ 'post' => $order_id, 'action' => 'edit' ], admin_url( 'post.php' ) ),
			'invoiceforge_regenerated'
		);
		wp_safe_redirect( admin_url( 'post.php?post=' . $order_id . '&action=edit' ) );
		exit;
	}

	/**
	 * Regenerates the packing slip PDF for an order (admin only).
	 *
	 * @param int $order_id Order ID.
	 */
	private function regenerate_packing_slip( int $order_id ): void {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			wp_die( esc_html__( 'Permission denied.', 'invoiceforge-for-woocommerce' ) );
		}

		$order = wc_get_order( $order_id );
		if ( ! $order ) {
			wp_die( esc_html__( 'Order not found.', 'invoiceforge-for-woocommerce' ) );
		}

		$generator = new \InvoiceForge\PDF\PDF_Generator();
		$generator->generate( new \InvoiceForge\PDF\Packing_Slip_Document( $order ) );

		wp_safe_redirect( admin_url( 'post.php?post=' . $order_id . '&action=edit' ) );
		exit;
	}

	/**
	 * Builds a nonce-protected download URL for an invoice.
	 *
	 * @param int    $order_id Order ID.
	 * @param string $action   One of: download_invoice, download_packing_slip.
	 * @param bool   $admin    True for admin URL, false for frontend.
	 * @return string
	 */
	public static function get_download_url( int $order_id, string $action = 'download_invoice', bool $admin = false ): string {
		$base = $admin ? admin_url( 'admin.php' ) : home_url( '/' );
		return wp_nonce_url(
			add_query_arg(
				[
					'invoiceforge_action' => $action,
					'order_id'            => $order_id,
				],
				$base
			),
			'invoiceforge_download_' . $order_id
		);
	}

	/**
	 * Builds a nonce-protected regenerate URL (admin only).
	 *
	 * @param int    $order_id Order ID.
	 * @param string $action   One of: regenerate_invoice, regenerate_packing_slip.
	 * @return string
	 */
	public static function get_regenerate_url( int $order_id, string $action = 'regenerate_invoice' ): string {
		return wp_nonce_url(
			add_query_arg(
				[
					'invoiceforge_action' => $action,
					'order_id'            => $order_id,
				],
				admin_url( 'admin.php' )
			),
			'invoiceforge_regenerate_' . $order_id
		);
	}
}
