<?php
/**
 * Order screen actions for generating and downloading invoices.
 *
 * @package InvoiceForge
 */

namespace InvoiceForge\Admin;

defined( 'ABSPATH' ) || exit;

/**
 * Adds "Generate Invoice", "Download Invoice", and "Download Packing Slip" actions
 * to the WooCommerce order edit page and the orders list.
 */
class Order_Actions {

	/**
	 * Adds custom actions to the WC order actions select box.
	 *
	 * @param array<string, string> $actions Existing actions.
	 * @return array<string, string>
	 */
	public function add_order_actions( array $actions ): array {
		$actions['invoiceforge_generate_invoice']      = __( 'Generate / Regenerate Invoice (PDF)', 'invoiceforge-for-woocommerce' );
		$actions['invoiceforge_generate_packing_slip'] = __( 'Generate / Regenerate Packing Slip (PDF)', 'invoiceforge-for-woocommerce' );
		return $actions;
	}

	/**
	 * Handles "Generate Invoice" action from the order edit screen.
	 *
	 * @param \WC_Order $order Current order.
	 */
	public function handle_generate_invoice( \WC_Order $order ): void {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			return;
		}
		$generator = new \InvoiceForge\PDF\PDF_Generator();
		$generator->generate( new \InvoiceForge\PDF\Invoice_Document( $order ) );

		/* translators: %s: order number */
		$order->add_order_note( sprintf( __( 'Invoice (PDF) generated by InvoiceForge.', 'invoiceforge-for-woocommerce' ) ) );
	}

	/**
	 * Handles "Generate Packing Slip" action from the order edit screen.
	 *
	 * @param \WC_Order $order Current order.
	 */
	public function handle_generate_packing_slip( \WC_Order $order ): void {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			return;
		}
		$generator = new \InvoiceForge\PDF\PDF_Generator();
		$generator->generate( new \InvoiceForge\PDF\Packing_Slip_Document( $order ) );

		$order->add_order_note( __( 'Packing slip (PDF) generated by InvoiceForge.', 'invoiceforge-for-woocommerce' ) );
	}

	/**
	 * Adds download links to the order list row actions.
	 *
	 * @param array<string, array<string, string>> $actions Existing list actions.
	 * @param \WC_Order                            $order   Current order.
	 * @return array<string, array<string, string>>
	 */
	public function add_list_actions( array $actions, \WC_Order $order ): array {
		$invoice_path = $order->get_meta( '_invoiceforge_invoice_path', true );

		if ( $invoice_path && file_exists( $invoice_path ) ) {
			$nonce_url = wp_nonce_url(
				add_query_arg(
					[
						'invoiceforge_action' => 'download_invoice',
						'order_id'            => $order->get_id(),
					],
					admin_url( 'admin-ajax.php' )
				),
				'invoiceforge_download_' . $order->get_id()
			);

			$actions['invoiceforge_invoice'] = [
				'url'    => $nonce_url,
				'name'   => __( 'Invoice PDF', 'invoiceforge-for-woocommerce' ),
				'action' => 'invoiceforge-invoice',
			];
		}

		return apply_filters( 'invoiceforge_admin_order_actions', $actions, $order );
	}
}
