name: Deploy to WordPress.org

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Deploy to wordpress.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install production dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: invoiceforge-for-woocommerce
