name: Deploy to WordPress.org

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: SVN Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install production dependencies
        run: composer install --no-dev --prefer-dist --no-progress --optimize-autoloader

      - name: Deploy to WordPress.org SVN
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: invoiceforge-for-woocommerce
